In [ ]:
import numpy as np
import cv2 as cv
import sys
import os

In [ ]:
import numpy as np

R = np.array([
    [0.28637946, 0.01401955, 0.95801371],
    [-0.06772315, 0.99768819, 0.00564437],
    [-0.95571982, -0.06649614, 0.28666685]
])


In [105]:
eig, v = np.linalg.eig(R)
rot_ax = v[:, 2].astype(np.float32)      
angle = np.arctan2(eig[0].imag, eig[0].real) 

/var/folders/m7/838zy1kd29xd54ddxq5nh4wm0000gn/T/ipykernel_27775/2217930498.py:2: ComplexWarning: Casting complex values to real discards the imaginary part
  rot_ax = v[:, 2].astype(np.float32)


In [106]:
rot_ax

array([-0.01157534, -0.97250694,  0.232586  ], dtype=float32)

In [107]:
angle

0.962648441634462

In [108]:
angle = angle * 180 / np.pi

In [8]:
import cv2
import numpy as np
# The rotation axis and vector as calculated from calibration
rotation_axis = np.array([-0.05138509, -0.98820245,  0.14427564])
rotation_axis = rotation_axis / np.linalg.norm(rotation_axis)
rotation_angle = 66.873739 * np.pi / 180

# Scaling the vector by the rotation angle
rotation_axis *= rotation_angle

# Converting the vector to a rotation matrix
rotation_matrix, _ = cv2.Rodrigues(rotation_axis)
print(rotation_matrix)

[[ 0.39436204 -0.10184685 -0.91329393]
 [ 0.16351691  0.98575662 -0.03932068]
 [ 0.90429022 -0.13383242  0.40539868]]
